/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyKS_GUI;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import QuanLyKS_DAL.LoaiPhong_DAL;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import com.ibm.icu.text.SimpleDateFormat;
import com.toedter.calendar.JCalendar;
import javax.swing.JOptionPane;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import QuanLyKS_DAL.Phong_DAL;
import QuanLyKS_DTO.CTDatPhong_DTO;
import QuanLyKS_DTO.LoaiPhong_DTO;
import QuanLyKS_BUS.CTDatPhong_BUS;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.InputMethodListener;
import java.awt.event.InputMethodEvent;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author MyPC
 */
public class frmDatPhong extends javax.swing.JInternalFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form DatPhong
     */
    public frmDatPhong() {
        initComponents();
       
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    
    //luu giu id dich vu duoc chon
    private static int idDV  = 0;		//save id DichVu selected
    private static int idLP  = 0;		//save id LoaiPhong selected
    private void initComponents() {
         	
    	//prepare list
    	ArrayList<LoaiPhong_DTO> listLP_DTO =  new ArrayList<LoaiPhong_DTO>();
        LoaiPhong_DAL lpDAL = new LoaiPhong_DAL();
        ResultSet rsLP = lpDAL.getListLoaiPhong();
    	    	
        txtTenKhachHang = new javax.swing.JTextField();
        TenKhachHang = new javax.swing.JLabel();
        cbxLoaiPhong = new javax.swing.JComboBox<>();
        JCalendar dtNgayTra = new JCalendar();
        JCalendar dtNgayNhan = new JCalendar();
        cbxMaPhong = new JComboBox<String>();
        cbxMaPhong.setInheritsPopupMenu(true);
        cbxMaPhong.setIgnoreRepaint(true);
        dtNgayNhan.addInputMethodListener(new InputMethodListener() {
        	public void caretPositionChanged(InputMethodEvent arg0) {
        	}
        	public void inputMethodTextChanged(InputMethodEvent arg0) {
        		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         		String NgayNhan = sdf.format( dtNgayNhan.getDate() );
         	 	String NgayTra = sdf.format( dtNgayTra.getDate() );
         		//load list Phong
                 ResultSet rslistPhong = Phong_DAL.selectCondition(idLP, NgayNhan, NgayTra);
                 try {    
               	  cbxMaPhong.removeAllItems();
                 	while(rslistPhong.next() ) {
                 		cbxMaPhong.addItem(rslistPhong.getString("MaPhong"));
                 		cbxMaPhong.getSelectedItem();
         		   }
         		} catch (SQLException e) {
         			// TODO Auto-generated catch block
         			e.printStackTrace();
         		}
        	}
        });
      
        dtNgayNhan.addPropertyChangeListener(new PropertyChangeListener() {
        	public void propertyChange(PropertyChangeEvent arg0) {
        		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         		String NgayNhan = sdf.format( dtNgayNhan.getDate() );
         	 	String NgayTra = sdf.format( dtNgayTra.getDate() );
         		//load list Phong
                ResultSet rslistPhong = Phong_DAL.selectCondition(idLP, NgayNhan, NgayTra);
                 try {    
               	  cbxMaPhong.removeAllItems();
                 	while(rslistPhong.next() ) {
                 		cbxMaPhong.addItem(rslistPhong.getString("MaPhong"));
                 		cbxMaPhong.getSelectedItem();
         		   }
         		} catch (SQLException e) {
         			// TODO Auto-generated catch block
         			e.printStackTrace();
         		}
        	}
        });
      
        
        cbxLoaiPhong.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent arg0) {
        		//get the value selected of cbx and using loop to scan Arraylist LoaiPhong
        		//after find the LoaiPhong selected, using function getMaLoaiPhong to get ID
        		String nameLP = (String) cbxLoaiPhong.getSelectedItem();
        		for(int i = 0; i < listLP_DTO.size(); i++) {
        			LoaiPhong_DTO dvCompare = listLP_DTO.get(i);
        			if(nameLP.equals( dvCompare.getTenLoaiPhong() ) )
        				idLP = dvCompare.getMaLoaiPhong();
        		}
        		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         		String NgayNhan = sdf.format( dtNgayNhan.getDate() );
         		String NgayTra = sdf.format( dtNgayTra.getDate() );
         		//load list Phong 
                 ResultSet rslistPhong = Phong_DAL.selectCondition(idLP, NgayNhan, NgayTra);
                  try {    
                	  cbxMaPhong.removeAllItems();
                  	while(rslistPhong.next() ) {
                  		cbxMaPhong.addItem(rslistPhong.getString("MaPhong"));
                   		cbxMaPhong.getSelectedItem();
          		   }
          		} catch (SQLException e) {
          			// TODO Auto-generated catch block
          			e.printStackTrace();
          		}
        	}
        });
        cbxLoaiPhong.setIgnoreRepaint(true);
        cbxLoaiPhong.setInheritsPopupMenu(true);
        NgayDatPhong = new javax.swing.JLabel();
        LoaiPhong = new javax.swing.JLabel();
        CMND = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        btnDongY = new javax.swing.JButton();
        btnDongY.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		       		
				SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
				String NgayNhan = sdf.format( dtNgayNhan.getDate() );
				String NgayTra = sdf.format( dtNgayTra.getDate() );
				
				String strMaPhong = (cbxMaPhong.getSelectedItem()).toString();
				int iMaPhong = Integer.parseInt(strMaPhong);
        		CTDatPhong_DTO ctdpDTO = new CTDatPhong_DTO(txtTenKhachHang.getText(), txtCMND.getText(), idDV, iMaPhong,NgayNhan, NgayTra);
        		
        		if(CTDatPhong_BUS.Insert(ctdpDTO) == true) {
        			JOptionPane.showMessageDialog(null, "Insert booking Success", "Success: " + "Success Mesage", JOptionPane.INFORMATION_MESSAGE);
        		}else {
        			JOptionPane.showMessageDialog(null, "Insert booking Fail", "Fail: " + "Success Mesage", JOptionPane.CLOSED_OPTION);
        		}
        	}
        });
       
        jLabel9 = new javax.swing.JLabel();
        GiaPhong = new javax.swing.JLabel();

        setTitle("ĐẶT PHÒNG");

        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });

        TenKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TenKhachHang.setText("T\u00CAN KH\u00C1CH H\u00C0NG");
        
       
       //Load list LoaiPhong
        try {
        	while(rsLP.next() ) {	
        		LoaiPhong_DTO lpTemp = new LoaiPhong_DTO(rsLP.getInt("MaLoaiPhong"), rsLP.getString("TenLoaiPhong"));
        		listLP_DTO.add(lpTemp);
        		cbxLoaiPhong.addItem(rsLP.getString("TenLoaiPhong"));
        		cbxLoaiPhong.getSelectedItem();
		   }
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace(); 
		}
      
        cbxLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiPhongActionPerformed(evt);
            }
        });

        NgayDatPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NgayDatPhong.setText("NG\u00C0Y NH\u1EACN - TR\u1EA2");

        LoaiPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LoaiPhong.setText("LO\u1EA0I PH\u00D2NG");

        CMND.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CMND.setText("CMND");

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        btnDongY.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDongY.setText("\u0110\u1ED3ng \u00FD");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setText("\u0110\u1EB6T PH\u00D2NG");

        GiaPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        GiaPhong.setText("M\u00C3 PH\u00D2NG");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(304)
        			.addComponent(jLabel9)
        			.addContainerGap(221, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(32)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(NgayDatPhong, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(CMND)
        				.addComponent(LoaiPhong, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        				.addComponent(GiaPhong)
        				.addComponent(TenKhachHang))
        			.addGap(13)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(cbxMaPhong, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(dtNgayNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(64)
        					.addComponent(dtNgayTra, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(txtTenKhachHang, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 474, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtCMND, Alignment.LEADING)
        				.addComponent(cbxLoaiPhong, 0, 486, Short.MAX_VALUE))
        			.addContainerGap())
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(406)
        			.addComponent(btnDongY)
        			.addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel9)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtTenKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TenKhachHang, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(28)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(dtNgayTra, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(dtNgayNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(99)
        					.addComponent(NgayDatPhong)))
        			.addGap(59)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(CMND)
        				.addComponent(txtCMND, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LoaiPhong)
        				.addComponent(cbxLoaiPhong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(GiaPhong)
        				.addComponent(cbxMaPhong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(35)
        			.addComponent(btnDongY)
        			.addGap(35))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void cbxLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiPhongActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND;
    private javax.swing.JLabel GiaPhong;
    private javax.swing.JLabel LoaiPhong;
    private javax.swing.JLabel NgayDatPhong;
    private javax.swing.JLabel TenKhachHang;
    private javax.swing.JButton btnDongY;
    private javax.swing.JComboBox<String> cbxLoaiPhong;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtTenKhachHang;
    private JComboBox<String> cbxMaPhong;
}
