/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyKS_GUI;
import java.sql.ResultSet;
import java.sql.SQLException;

import QuanLyKS_DAL.DichVu_DAL;
import QuanLyKS_DAL.LoaiPhong_DAL;

/**
 *
 * @author MyPC
 */
public class frmDatPhong extends javax.swing.JInternalFrame {

    /**
     * Creates new form DatPhong
     */
    public frmDatPhong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	//prepare list
    	DichVu_DAL dvDAL = new DichVu_DAL();
        ResultSet rsListDV = dvDAL.getListDV();
       
        LoaiPhong_DAL lpDAL = new LoaiPhong_DAL();
        ResultSet rsLP = lpDAL.getListLoaiPhong();
    	
    	
    	
        txtTenKhachHang = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        TenKhachHang = new javax.swing.JLabel();
        NgaySinh = new javax.swing.JLabel();
        cbxLoaiPhong = new javax.swing.JComboBox<>();
        txtNgayDatPhong = new javax.swing.JTextField();
        NgayDatPhong = new javax.swing.JLabel();
        MaKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtMaPhong = new javax.swing.JTextField();
        LoaiPhong = new javax.swing.JLabel();
        CMND = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        TrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        btnDongY = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JTextField();
        GiaPhong = new javax.swing.JLabel();
        MaPhong = new javax.swing.JLabel();
        cbxDichVu = new javax.swing.JComboBox<>();
        DichVu = new javax.swing.JLabel();
        MaDichVu = new javax.swing.JLabel();
        txtMaDichVu = new javax.swing.JTextField();

        setTitle("đặt phòng");

        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        TenKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TenKhachHang.setText("TÊN KHÁCH HÀNG");

        NgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NgaySinh.setText("NGÀY SINH");
        
       
       
        try {
        	while(rsLP.next() ) {
        		cbxLoaiPhong.addItem(rsLP.getString("TenLoaiPhong"));
        		cbxLoaiPhong.getSelectedItem();
		   }
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
      
        cbxLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiPhongActionPerformed(evt);
                
            }
        });

        txtNgayDatPhong.setText("auto load");

        NgayDatPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NgayDatPhong.setText("NGÀY ĐẶT PHÒNG");

        MaKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MaKhachHang.setText("MÃ KHÁCH HÀNG");

        txtMaKhachHang.setText("auto load");

        txtMaPhong.setText("auto load");
        txtMaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhongActionPerformed(evt);
            }
        });

        LoaiPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LoaiPhong.setText("LOẠI PHÒNG");

        CMND.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CMND.setText("CMND");

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        TrangThai.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TrangThai.setText("TRẠNG THÁI");

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn", "Hết" }));

        btnDongY.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDongY.setText("đồng ý");

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThoat.setText("thoát");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setText("đặt phòng");

        txtGiaPhong.setText("auto load");

        GiaPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        GiaPhong.setText("GIÁ PHÒNG");

        MaPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MaPhong.setText("MÃ PHÒNG");

        
        
        try {
        	while(rsListDV.next() ) {
        		cbxDichVu.addItem(rsListDV.getString("TenDichVu"));
        		cbxDichVu.getSelectedItem();
		   }
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        

        DichVu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DichVu.setText("DỊCH VỤ");

        MaDichVu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MaDichVu.setText("MÃ DỊCH VỤ");

        txtMaDichVu.setText("auto load");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NgayDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MaKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TenKhachHang, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DichVu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MaDichVu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CMND, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LoaiPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TrangThai)
                    .addComponent(GiaPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbxTrangThai, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxLoaiPhong, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCMND, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDichVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayDatPhong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDichVu)
                    .addComponent(txtGiaPhong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(btnDongY)
                .addGap(82, 82, 82)
                .addComponent(btnThoat)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaKhachHang)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenKhachHang)
                    .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgaySinh)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgayDatPhong)
                    .addComponent(txtNgayDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DichVu)
                    .addComponent(cbxDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaDichVu)
                    .addComponent(txtMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMND)
                    .addComponent(txtCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaPhong)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoaiPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TrangThai)
                    .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GiaPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDongY)
                    .addComponent(btnThoat))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void cbxLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiPhongActionPerformed

    private void txtMaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhongActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND;
    private javax.swing.JLabel DichVu;
    private javax.swing.JLabel GiaPhong;
    private javax.swing.JLabel LoaiPhong;
    private javax.swing.JLabel MaDichVu;
    private javax.swing.JLabel MaKhachHang;
    private javax.swing.JLabel MaPhong;
    private javax.swing.JLabel NgayDatPhong;
    private javax.swing.JLabel NgaySinh;
    private javax.swing.JLabel TenKhachHang;
    private javax.swing.JLabel TrangThai;
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbxDichVu;
    private javax.swing.JComboBox<String> cbxLoaiPhong;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaDichVu;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtNgayDatPhong;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
