/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyKS_GUI;
import java.sql.ResultSet;
import java.sql.SQLException;

import QuanLyKS_DAL.DichVu_DAL;
import QuanLyKS_DAL.LoaiPhong_DAL;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.ibm.icu.text.SimpleDateFormat;
import com.toedter.calendar.JCalendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import QuanLyKS_DTO.CTDatPhong_DTO;
import QuanLyKS_BUS.CTDatPhong_BUS;
/**
 *
 * @author MyPC
 */
public class frmDatPhong extends javax.swing.JInternalFrame {

    /**
     * Creates new form DatPhong
     */
    public frmDatPhong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	//prepare list
    	DichVu_DAL dvDAL = new DichVu_DAL();
        ResultSet rsListDV = dvDAL.getListDV();
       
        LoaiPhong_DAL lpDAL = new LoaiPhong_DAL();
        ResultSet rsLP = lpDAL.getListLoaiPhong();
    	
    	
    	
        txtTenKhachHang = new javax.swing.JTextField();
        TenKhachHang = new javax.swing.JLabel();
        cbxLoaiPhong = new javax.swing.JComboBox<>();
        NgayDatPhong = new javax.swing.JLabel();
        LoaiPhong = new javax.swing.JLabel();
        CMND = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        btnDongY = new javax.swing.JButton();
        JCalendar dtNgayTra = new JCalendar();
        JCalendar dtNgayNhan = new JCalendar();
        btnDongY.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		CTDatPhong_BUS ctdpBUS = new CTDatPhong_BUS();        		
				SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
				String NgayNhan = sdf.format( dtNgayNhan.getDate() );
				String NgayTra = sdf.format( dtNgayTra.getDate() );
        		CTDatPhong_DTO ctdpDTO = new CTDatPhong_DTO(txtTenKhachHang.getText(), txtCMND.getText(), cbxDichVu.getSelectedIndex(), NgayNhan, NgayTra);
        		
        		if(CTDatPhong_BUS.Insert(ctdpDTO) == true) {
        			JOptionPane.showMessageDialog(null, "Insert booking Success", "Success: " + "Success Mesage", JOptionPane.INFORMATION_MESSAGE);
        		}else {
        			JOptionPane.showMessageDialog(null, "Insert booking Fail", "Fail: " + "Success Mesage", JOptionPane.CLOSED_OPTION);
        		}
        		
        	}
        });
        btnThoat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JTextField();
        GiaPhong = new javax.swing.JLabel();
        cbxDichVu = new javax.swing.JComboBox<>();
        DichVu = new javax.swing.JLabel();

        setTitle("đặt phòng");

        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });

        TenKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TenKhachHang.setText("TÊN KHÁCH HÀNG");
        
       
       
        try {
        	while(rsLP.next() ) {
        		cbxLoaiPhong.addItem(rsLP.getString("TenLoaiPhong"));
        		cbxLoaiPhong.getSelectedItem();
		   }
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
      
        cbxLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiPhongActionPerformed(evt);
                
            }
        });

        NgayDatPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NgayDatPhong.setText("NGÀY NHẬN PHÒNG");

        LoaiPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LoaiPhong.setText("LOẠI PHÒNG");

        CMND.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CMND.setText("CMND");

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        btnDongY.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDongY.setText("đồng ý");

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnThoat.setText("thoát");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setText("đặt phòng");

        txtGiaPhong.setText("auto load");

        GiaPhong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        GiaPhong.setText("GIÁ PHÒNG");

        
        
        try {
        	while(rsListDV.next() ) {
        		cbxDichVu.addItem(rsListDV.getString("TenDichVu"));
        		cbxDichVu.getSelectedItem();
		   }
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        

        DichVu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DichVu.setText("DỊCH VỤ");
        
        
        
        JLabel lblNgyTrPhng = new JLabel();
        lblNgyTrPhng.setText("NGÀY TRẢ PHÒNG");
        lblNgyTrPhng.setFont(new Font("Times New Roman", Font.BOLD, 12));
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(0, 350, Short.MAX_VALUE)
        			.addComponent(jLabel9)
        			.addGap(221))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(289)
        			.addComponent(btnDongY)
        			.addGap(57)
        			.addComponent(btnThoat)
        			.addContainerGap(247, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addGap(37)
        			.addComponent(NgayDatPhong, GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(37)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(CMND)
        					.addGap(131)
        					.addComponent(txtCMND, GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(DichVu)
        					.addGap(119)
        					.addComponent(cbxDichVu, 0, 503, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(TenKhachHang)
        					.addPreferredGap(ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
        					.addComponent(txtTenKhachHang, GroupLayout.PREFERRED_SIZE, 373, GroupLayout.PREFERRED_SIZE)
        					.addGap(141))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblNgyTrPhng, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)
        					.addGap(50)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(dtNgayNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(dtNgayTra, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap(315, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(LoaiPhong, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        						.addComponent(GiaPhong))
        					.addGap(60)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txtGiaPhong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(462))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(cbxLoaiPhong, 0, 503, Short.MAX_VALUE)
        							.addContainerGap())))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel9)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtTenKhachHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(TenKhachHang, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(NgayDatPhong)
        				.addComponent(dtNgayNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(dtNgayTra, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(71)
        					.addComponent(lblNgyTrPhng)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cbxDichVu, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DichVu))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtCMND, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(CMND))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cbxLoaiPhong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(LoaiPhong))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(GiaPhong)
        				.addComponent(txtGiaPhong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(12)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnThoat)
        				.addComponent(btnDongY))
        			.addGap(70))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void cbxLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiPhongActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND;
    private javax.swing.JLabel DichVu;
    private javax.swing.JLabel GiaPhong;
    private javax.swing.JLabel LoaiPhong;
    private javax.swing.JLabel NgayDatPhong;
    private javax.swing.JLabel TenKhachHang;
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbxDichVu;
    private javax.swing.JComboBox<String> cbxLoaiPhong;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtTenKhachHang;
}
